
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-6pm-3
owner: ucsb-cs156-w24
repo_name: team02-w24-6pm-3
pull_requests: [{"author":{"id":"U_kgDOBX3m_g","is_bot":false,"login":"welaalice","name":"Towela Phiri"},"headRefName":"Towela-UCSBOrganizations","number":49,"title":"TP - Created database table for UCSBOrganizations","url":"https://github.com/ucsb-cs156-w24/team02-w24-6pm-3/pull/49"},{"author":{"id":"MDQ6VXNlcjg2NzQzODY1","is_bot":false,"login":"Jenniebn","name":"Jennie Wu"},"headRefName":"JW-HelpRequest","number":48,"title":"Jw help request","url":"https://github.com/ucsb-cs156-w24/team02-w24-6pm-3/pull/48"},{"author":{"id":"U_kgDOBh72PQ","is_bot":false,"login":"andyjin1","name":"Andy Jin"},"headRefName":"AJ-MenuItemReviewController","number":46,"title":"AJ - Added MenuItemReviewController and tests","url":"https://github.com/ucsb-cs156-w24/team02-w24-6pm-3/pull/46"}]
