
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-6pm-3
owner: ucsb-cs156-w24
repo_name: team02-w24-6pm-3
pull_requests: [{"author":{"id":"U_kgDOBh72PQ","is_bot":false,"login":"andyjin1","name":"Andy Jin"},"headRefName":"AJ-MenuItemReview-Final","number":66,"title":"AJ - Added all endpoints in Menu Item Reviews Controller","url":"https://github.com/ucsb-cs156-w24/team02-w24-6pm-3/pull/66"},{"author":{"id":"U_kgDOBX3m_g","is_bot":false,"login":"welaalice","name":"Towela Phiri"},"headRefName":"TP-UCSBOrganizations-Controller","number":61,"title":"TP - UCSBOrganizations Controller and Tests","url":"https://github.com/ucsb-cs156-w24/team02-w24-6pm-3/pull/61"}]
